### ISSUE TITLE
Request to merge `configurator.py` and `main.py`

### ISSUE THREAD

**Issue by not-nef** [sumeshir26/TimerX#24]
If we dont do that, we cant change the theme in the settings window because of circular imports. pls give permission to merge the scripts. thx

**Comment by not-nef** [comment]
To make sure the code isnt too messy i made this:
![Screenshot 2021-12-25 103410](https://user-images.githubusercontent.com/83908932/147382235-c672489f-c7d7-4416-8641-10861ac01d5b.png)

**Comment by im-coder-lg** [comment]
@not-nef first off, I think it might increase the size of the main.py file, second, it could extend code lines thereby making it too long(I expect a TL;DR for long lines of code) and that could make finding code harder.
But, if we are able to make a better link between the main.py and configurator.py, we could be in luck since the files will share data with each other like theming, icons, properties, metadata, etc.
What do you think? Also, since the screenshot is too small, can you try posting the code as a public [Gist](https://gist.github.com) and share the link here?
Moreover, I wonder if we merge the configurator and the settings together, or adding a link to settings in the configurator window, any ideas?

**Comment by not-nef** [comment]
@im-coder-lg vscode users can collapse functions for a better overview.

btw we literally cant change the theme in the settings if they are in seperate files. its literally impossible

**Comment by not-nef** [comment]
https://gist.github.com/not-nef/ed6e612634df8638159e07adf9f1df8f

this is the current main file, it has a settings page with working theme switching ^-^

**Comment by im-coder-lg** [comment]
> btw we literally cant change the theme in the settings if they are in seperate files. its literally impossible

Can you _link_ two files?

**Comment by im-coder-lg** [comment]
> https://gist.github.com/not-nef/ed6e612634df8638159e07adf9f1df8f

That works, but it seems to take some time to load upon starting, but I think it's normal. Plus, icons get synced, and more.
Can we make a PR to the `settings` branch @sumeshir26? 400 lines of code but I think it's worth it! Also, push _your_ local changes to the branch so that @not-nef can get the changes and add those codes to the main file himself.
@not-nef can you add a bit more spacing between icons in the settings window? Kinda looks cramped, if you ask me.

**Comment by im-coder-lg** [comment]
Let's add a toggle for blur(exclusively for Windows) too.

**Comment by sumeshir26** [comment]
I cant. I am out of townn so I cant get to my computer currenty

**Comment by not-nef** [comment]
> > https://gist.github.com/not-nef/ed6e612634df8638159e07adf9f1df8f
> 
> That works, but it seems to take some time to load upon starting, but I think it's normal. Plus, icons get synced, and more. Can we make a PR to the `settings` branch @sumeshir26? 400 lines of code but I think it's worth it! Also, push _your_ local changes to the branch so that @not-nef can get the changes and add those codes to the main file himself. @not-nef can you add a bit more spacing between icons in the settings window? Kinda looks cramped, if you ask me.

lets move this to the pr

**Comment by im-coder-lg** [comment]
> I cant. I am out of townn so I cant get to my computer currenty

I could help. We could add the toggle exclusively to Windows, maybe through the platform code.

**Comment by not-nef** [comment]
platform code?

**Comment by sumeshir26** [comment]
Platform.system()
